import React, { useEffect, useState } from "react";
import Widgets from "../../components/Widgets";
import { useRouter } from "next/router";
import Sidebar from "../../components/Sidebar";
import Head from "next/head";
import CommentModal from "../../components/CommentModal";
import { ArrowLeftIcon } from "@heroicons/react/outline";
import Post from "../../components/Post";
import {
  collection,
  doc,
  onSnapshot,
  orderBy,
  query,
} from "firebase/firestore";
import { db } from "../../firebase";
import Comment from "../../components/Comment";

const PostPage = () => {
  const router = useRouter();
  const { id } = router.query;
  const [post, setPost] = useState(null);
  const [comments, setComments] = useState([]);

  //get the post data
  useEffect(() => {
    onSnapshot(doc(db, "posts", id), (snapshot) => setPost(snapshot));
  }, [db, id]);

  //get the comments of the post

  useEffect(() => {
    onSnapshot(
      query(
        collection(db, "posts", id, "comments"),
        orderBy("timestamp", "desc")
      ),
      (snapshot) => setComments(snapshot.docs)
    );
  }, [db, id]);

  return (
    <div>
      <Head>
        <title>Post Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen  mx-auto ">
        {/* Sidebar*/}
        <Sidebar />
        {/* //=========================== */}
        <div className="xl:ml-[370px] border-l border-r border-gray-200 xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl">
          <div className="flex items-center py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
            <div
              className="hoverEffect"
              onClick={() => {
                router.push("/");
              }}
            >
              <ArrowLeftIcon className="h-5 ml-4 mt-4 sm:mt-4 sm:ml-4" />
            </div>
            <h2 className="text-lg sm:text-xl font-bold cursor-pointer sm:ml-2">
              Tweet
            </h2>
            <div className="hoverEffect flex items-center justify-center px-0 ml-auto w-9 h-9" />
          </div>

          <Post id={id} post={post} />
          {comments.length > 0 && (
            <div className="">
              {comments.map((comment) => {
              return  <Comment
                  key={comment.id}
                  id={comment.id}
                  comment={comment.data()}
                />;
              })}
            </div>
          )}
        </div>
        {/* Widgets */}
        <Widgets />
        {/* Modal */}
        <CommentModal />
      </main>
    </div>
  );
};

export default PostPage;
