import Widgets from "../components/Widgets";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Head from "next/head";

export default function Home({ newsResults }) {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen  mx-auto ">
        {/* Sidebar*/}
        <Sidebar />

        {/* Feed */}
        <Feed />
        {/* Widgets */}
        <Widgets newsResults={newsResults?.article} />
        {/* Modal */}
      </main>
    </div>
  );
}
//https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
    ).then((res) => res.json());
   
  return {
    props: {
      newsResults,
    },
  };
}
