import Widgets from "../components/Widgets";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Head from "next/head";
import CommentModal from "../components/CommentModal";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen  mx-auto ">
        {/* Sidebar*/}
        <Sidebar />

        {/* Feed */}
        <Feed />
        {/* Widgets */}
        <Widgets />
        {/* Modal */}
        <CommentModal />
      </main>
    </div>
  );
}
