import Widgets from "../components/Widgets";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Head from "next/head";
import Modal from "../components/Modal";

export default function Home() {
  //   const [articles,setArticles] = useState([]);

  // useEffect(()=>{
  // const fetchData=async()=>{
  // const res=await fetch("https://saurav.tech/NewsAPI/top-headlines/category/business/us.json")
  // const data= await res.json()
  // setArticles(data.articles)
  // }

  // fetchData()
  // },[])

  // console.log(articles);

  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen  mx-auto ">
        {/* Sidebar*/}
        <Sidebar />

        {/* Feed */}
        <Feed />
        {/* Widgets */}
        <Widgets />
        {/* Modal */}
        <Modal />
      </main>
    </div>
  );
}
//https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

// export async function getServerSideProps() {
//   const newsResults = await fetch(
//     "https://saurav.tech/NewsAPI/top-headlines/category/health/in.json"
//     ).then((res) => res.json());

//   return {
//     props: {
//       newsResults,
//     },
//   };
// }
